### ISSUE TITLE
a question 

### ISSUE THREAD

**Issue by alna0077** [alna0077/grid-layout-with-flex-components#1]
hi @abhaysharma , when I wanted to save/publish the page, I could only do it after I changed the source to master. Just wanted to double-check if this is a good practice. Thanks

**Comment by abhaysharma** [comment]
@alna0077 yes, you need to select the source out of the dropdown which would be either main or master.

**Comment by alna0077** [comment]
hanks @abhaysharma so I should always select master when I fork a repository, is it right?

**Comment by abhaysharma** [comment]
@alna0077 yes, that is correct.
